[ActiveSupport PAR]
; Global primary clocks
GLOBAL_PRIMARY_USED = 6;
; Global primary clock #0
GLOBAL_PRIMARY_0_SIGNALNAME = u_lpddr3/pll_clk_out;
GLOBAL_PRIMARY_0_DRIVERTYPE = PLL;
GLOBAL_PRIMARY_0_LOADNUM = 52;
; Global primary clock #1
GLOBAL_PRIMARY_1_SIGNALNAME = ADC_CLK_c;
GLOBAL_PRIMARY_1_DRIVERTYPE = PLL;
GLOBAL_PRIMARY_1_LOADNUM = 1;
; Global primary clock #2
GLOBAL_PRIMARY_2_SIGNALNAME = CLK_100MHZ_c;
GLOBAL_PRIMARY_2_DRIVERTYPE = CLK_PIN;
GLOBAL_PRIMARY_2_LOADNUM = 4;
; Global primary clock #3
GLOBAL_PRIMARY_3_SIGNALNAME = ETH_REFCLK_c;
GLOBAL_PRIMARY_3_DRIVERTYPE = PIO;
GLOBAL_PRIMARY_3_LOADNUM = 7;
; Global primary clock #4
GLOBAL_PRIMARY_4_SIGNALNAME = ULPI_CLK_c;
GLOBAL_PRIMARY_4_DRIVERTYPE = CLK_PIN;
GLOBAL_PRIMARY_4_LOADNUM = 15;
; Global primary clock #5
GLOBAL_PRIMARY_5_SIGNALNAME = reset_sync_rgmii[2];
GLOBAL_PRIMARY_5_DRIVERTYPE = SLICE;
GLOBAL_PRIMARY_5_LOADNUM = 0;
; I/O Bank 0 Usage
BANK_0_USED = 2;
BANK_0_AVAIL = 24;
BANK_0_VCCIO = 2.5V;
BANK_0_VREF1 = NA;
BANK_0_VREF2 = NA;
; I/O Bank 1 Usage
BANK_1_USED = 4;
BANK_1_AVAIL = 32;
BANK_1_VCCIO = 3.3V;
BANK_1_VREF1 = NA;
BANK_1_VREF2 = NA;
; I/O Bank 2 Usage
BANK_2_USED = 27;
BANK_2_AVAIL = 32;
BANK_2_VCCIO = 2.5V;
BANK_2_VREF1 = NA;
BANK_2_VREF2 = NA;
; I/O Bank 3 Usage
BANK_3_USED = 27;
BANK_3_AVAIL = 32;
BANK_3_VCCIO = 2.5V;
BANK_3_VREF1 = NA;
BANK_3_VREF2 = NA;
; I/O Bank 6 Usage
BANK_6_USED = 2;
BANK_6_AVAIL = 32;
BANK_6_VCCIO = 3.3V;
BANK_6_VREF1 = NA;
BANK_6_VREF2 = NA;
; I/O Bank 7 Usage
BANK_7_USED = 12;
BANK_7_AVAIL = 32;
BANK_7_VCCIO = 3.3V;
BANK_7_VREF1 = NA;
BANK_7_VREF2 = NA;
; I/O Bank 8 Usage
BANK_8_USED = 1;
BANK_8_AVAIL = 13;
BANK_8_VCCIO = 3.3V;
BANK_8_VREF1 = NA;
BANK_8_VREF2 = NA;
